apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: mysql  
  namespace: asiayo  
spec:  
  replicas: 2  
  selector:  
    matchLabels:  
      app: mysql  
  template:  
    metadata:  
      labels:  
        app: mysql  
    spec:  
      containers:  
        - name: mysql  
          image: mysql:8.0  
          env:  
            - name: MYSQL_ROOT_PASSWORD  
              value: "xxx"  
          ports:  
            - containerPort: 3306  
          volumeMounts:  
            - name: mysql-storage  
              mountPath: /var/lib/mysql  
      volumes:  
        - name: mysql-storage  
          persistentVolumeClaim:  
            claimName: mysql-pvc  
---  
apiVersion: v1  
kind: Service  
metadata:  
  name: mysql  
  namespace: asiayo  
spec:  
  selector:  
    app: mysql  
  ports:  
    - protocol: TCP  
      port: 3306  
      targetPort: 3306  
  type: ClusterIP  
---  
apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: mysql-pvc  
  namespace: asiayo  
spec:  
  accessModes:  
    - ReadWriteOnce  
  resources:  
    requests:  
      storage: 10Gi  
