apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: mysql-pv  
spec:  
  capacity:  
    storage: 10Gi  
  accessModes:  
    - ReadWriteOnce  
  awsElasticBlockStore: ebs-vol-id  
---  
apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: web-pv  
spec:  
  capacity:  
    storage: 10Gi  
  accessModes:  
    - ReadWriteOnce  
  awsElasticBlockStore: ebs-vol-id
