apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: web  
  namespace: asiayo  
spec:  
  replicas: 3  
  selector:  
    matchLabels:  
      app: web  
  template:  
    metadata:  
      labels:  
        app: web  
    spec:  
      containers:  
        - name: web  
          image: nginx:latest  
          ports:  
            - containerPort: 80  
          volumeMounts:  
            - name: web-storage  
              mountPath: /usr/share/nginx/html  
      volumes:  
        - name: web-storage  
          persistentVolumeClaim:  
            claimName: web-pvc  
---  
apiVersion: v1  
kind: Service  
metadata:  
  name: web  
  namespace: asiayo  
spec:  
  selector:  
    app: web  
  ports:  
    - protocol: TCP  
      port: 80  
      targetPort: 80  
  type: ClusterIP  
---  
apiVersion: networking.k8s.io/v1  
kind: Ingress  
metadata:  
  name: web-ingress  
  namespace: asiayo  
spec:  
  rules:  
    - host: asiayo.com 
      http:  
        paths:  
          - path: /  
            pathType: Prefix  
            backend:  
              service:  
                name: web  
                port:  
                  number: 80  
---  
apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: web-pvc  
  namespace: asiayo  
spec:  
  accessModes:  
    - ReadWriteOnce  
  resources:  
    requests:  
      storage: 10Gi  
